#### --->   To run a program line, press 'Ctrl + Enter'    <---

In [1]:
import numpy as npy

# One dimension array
ar1 = npy.array([12, 34, 56])
print(ar1)
print()

# Two dimension array
ar2 = npy.array([[12, 34, 56], [34,33, 67]])
print(ar2)
print()

# Three dimension array, by specifying the number of dimensions (ndmin)
ar3 = npy.array([[12, 34, 56], [34,33,67]], ndmin=3)
print(ar3)
print()

# Specify the data type of the array(s) in dtype
ar4 = npy.array([12,34,56], dtype=str)
print(ar4)
print()

# Increase the values of an array by X
ar5 = npy.array([1,23,45,6])
ar5_new = ar5 + 5
print(ar5_new)
print()

# Printing values from dimensional arrays
print(ar1[1])
print(ar2[1,2])

[12 34 56]

[[12 34 56]
 [34 33 67]]

[[[12 34 56]
  [34 33 67]]]

['12' '34' '56']

[ 6 28 50 11]

34
67
