# Series

In [2]:
import pandas as pd
import numpy as npy

sr = pd.Series([12, 34, 56, 78, 90])
print(sr)
print()

# Change the index numbers
sr = pd.Series([12,34,56,78,90], index=[1,2,3,4,5])
print(sr)
print()

sr = pd.Series([12,34,56,78,90], index=['a', 'b', 'c', 'd', 'e'])
print(sr)
print()

# Change the data type of the series, using dtype
sr = pd.Series([12,34,56,78,90], index=['a', 'b', 'c', 'd', 'e'], dtype = complex)
print(sr)
print()

0    12
1    34
2    56
3    78
4    90
dtype: int64

1    12
2    34
3    56
4    78
5    90
dtype: int64

a    12
b    34
c    56
d    78
e    90
dtype: int64

a    12.000000+0.000000j
b    34.000000+0.000000j
c    56.000000+0.000000j
d    78.000000+0.000000j
e    90.000000+0.000000j
dtype: complex128



# Numpy array to Series

In [3]:
# Convert numpy array to panda series, with indexes
ar = npy.array([1,2,3,4,5,6])
sr = pd.Series(data = ar, index = ['a', 'b', 'c', 'd', 'e', 'f'])

print(sr)
print()

# You cannot pass more than a single dimensional array into a Series
# To pass a multi-dimensional array, we use DataFrames instead

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int32



# Retrieve value(s) from Series

In [4]:
# Print a value from a Series
sr = pd.Series([12,23,34,45,56,67], index = ['A', 'B', 'C', 'D', 'E', 'F'])
print(sr['E'])
print(sr[4])
print()

# But if the indexes are change to integers, then we use the '.loc[index]' for user-defined indexes
sr = pd.Series([12,23,34,45,56,67], index = [1, 2, 3, 4, 5, 6])
print(sr.loc[4])
print()

# And if we use the '.iloc[index]', we use the predefined indexes
print(sr.iloc[4])
print()

56
56

45

56



# DataFrames

In [5]:
# Create a DataFrame
df = pd.DataFrame({'Age': [17, 22, 45], 
                   'Color': ['Red', 'Blue', 'Yellow']
                  })
print(df)
print()

df
print()

   Age   Color
0   17     Red
1   22    Blue
2   45  Yellow




# Make DataFrame from a Numpy array

In [6]:
ar = npy.array([[17, 22, 65],
                [56, 87, 21],
                [77, 24, 69]
               ])
df2 = pd.DataFrame(data = ar)
print(df2)
print()


    0   1   2
0  17  22  65
1  56  87  21
2  77  24  69



# Define column and/or row names in DataFrame

In [7]:
# Define the column names, and the rows (indexes)
df3 = pd.DataFrame(data = ar, columns = ['C1', 'C2', 'C3'], index = ['A', 'B', 'C'])
print(df3)
print()


   C1  C2  C3
A  17  22  65
B  56  87  21
C  77  24  69



# Retrieve value(s) from DataFrame

In [8]:
# Get a specific output (column) from a DataFrame
print(df3['C1'])
print()

# Get a specific output (row) from a DataFrame
print(df3.loc['C'])        # User-defined index (.loc[index])
print()
print(df3.iloc[1])         # Pre-defined index  (.iloc[index])
print()

# Get a specific output (value) from a DataFrame
print(df3.values)
print()

print(df3.values[1,2])
print()

A    17
B    56
C    77
Name: C1, dtype: int32

C1    77
C2    24
C3    69
Name: C, dtype: int32

C1    56
C2    87
C3    21
Name: B, dtype: int32

[[17 22 65]
 [56 87 21]
 [77 24 69]]

21

